services:

  timescale-db:
    image: timescale/timescaledb-ha:pg16
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/home/postgres/pgdata/data
