name: prometheus

services:
  prometheus:
    image: prom/prometheus
    secrets:
      - source: supabase-key
        target: SUPABASE_SERVICE_ROLE_KEY
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./rules.yml:/etc/prometheus/rules.yml"
    networks:
      - monitoring
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter
    networks:
      - monitoring
    ports:
      - 9100:9100

  alert-manager:
    image: prom/alertmanager
    secrets:
      - source: discord-url
        target: DISCORD_WEBHOOK_URL
    volumes:
      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - monitoring
    ports:
      - 9093:9093

networks:
  monitoring:
    driver: bridge

secrets:
  discord-url:
    file: ./secrets/DISCORD_WEBHOOK_URL
  supabase-key:
    file: ./secrets/SUPABASE_SERVICE_ROLE_KEY

