global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alert-manager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: node
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: supabase
    metrics_path: "/customer/v1/privileged/metrics"
    scheme: https
    basic_auth:
      username: "service_role"
      password_file: /run/secrets/SUPABASE_SERVICE_ROLE_KEY
    static_configs:
      - targets:
        - nqybkfptwydjndfbrdwz.supabase.co:443
        labels:
          group: "NERDb"

