version: '1'
services:

  neo4j:
    build: ./neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_mode=SINGLE
      #- NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_logs_query_enabled=true
      - NEO4J_dbms_logs_query_parameter__logging__enabled=true
      - NEO4J_dbms_logs_query_time__logging__enabled=true
      - NEO4J_dbms_logs_query_allocation__logging__enabled=true
      - NEO4J_dbms_logs_query_page__logging__enabled=true
    volumes:
      - ./data:/data
      - ./logs/neo4j:/var/lib/neo4j/logs
      - ./import:/import

volumes:
  temp:
    driver: local
    driver_opts:
      device: $TEMP
      o: bind
      type: none