ALTER TABLE player.alliance
ADD COLUMN IF NOT EXISTS creator_corporation_id INTEGER,
  ADD COLUMN IF NOT EXISTS creator_id INTEGER,
  ADD COLUMN IF NOT EXISTS date_founded TIMESTAMP,
  ADD COLUMN IF NOT EXISTS executor_corporation_id INTEGER,
  ADD COLUMN IF NOT EXISTS faction_id INTEGER,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS ticker TEXT;

DO $$ BEGIN CREATE TYPE player.gender AS ENUM ('female', 'male');

EXCEPTION
WHEN duplicate_object THEN NULL;

END $$;

ALTER TABLE player.character
ADD COLUMN IF NOT EXISTS alliance_id INTEGER,
  ADD COLUMN IF NOT EXISTS birthday TIMESTAMP,
  ADD COLUMN IF NOT EXISTS bloodline_id INTEGER,
  ADD COLUMN IF NOT EXISTS corporation_id INTEGER,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS faction_id INTEGER,
  ADD COLUMN IF NOT EXISTS gender player.gender,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS race_id INTEGER,
  ADD COLUMN IF NOT EXISTS security_status NUMERIC(17, 2),
  ADD COLUMN IF NOT EXISTS title TEXT;

ALTER TABLE player.corporation
ADD COLUMN IF NOT EXISTS alliance_id INTEGER,
  ADD COLUMN IF NOT EXISTS ceo_id INTEGER,
  ADD COLUMN IF NOT EXISTS creator_id INTEGER,
  ADD COLUMN IF NOT EXISTS date_founded TIMESTAMP,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS faction_id INTEGER,
  ADD COLUMN IF NOT EXISTS home_station_id INTEGER,
  ADD COLUMN IF NOT EXISTS member_count INTEGER,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS shares INTEGER,
  ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(17, 2),
  ADD COLUMN IF NOT EXISTS ticker TEXT,
  ADD COLUMN IF NOT EXISTS url TEXT,
  ADD COLUMN IF NOT EXISTS war_eligible BOOLEAN;
