services:

  db:
    image: postgres:16.3
    container_name: db
    user: postgres
    restart: always
    environment:
      POSTGRES_DB: nerdb
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    shm_size: 4gb
    volumes:
      - pgdata:/var/lib/postgresql/data
