services:
  mongodb:
    image: mongodb/mongodb-enterprise-server:7.0.2-ubi9
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
